# Generated by Django 2.2.5 on 2019-09-30 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_completedtask'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_text', models.CharField(max_length=200)),
                ('task_status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_task', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='CompletedTask',
        ),
        migrations.AddField(
            model_name='todo',
            name='completed_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todo',
            name='note',
            field=models.CharField(default='NA', max_length=500),
        ),
        migrations.AddField(
            model_name='subtask',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ToDo'),
        ),
        migrations.AddField(
            model_name='todo',
            name='task_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.TaskType'),
        ),
    ]
