# Generated by Django 2.2.5 on 2019-10-01 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20191001_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='task_note',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
